export const WORKSPACE_HEADER_HEIGHT = 64;
export const WORKSPACE_SIDEBAR_WIDTH = 256;
export const WORKSPACE_SIDEBAR_COLLAPSED_WIDTH = 72;
export const WORKSPACE_MOBILE_SIDEBAR_WIDTH = 280;
export const WORKSPACE_RIGHT_RAIL_WIDTH = 320;
