@startuml
skinparam linetype ortho
skinparam activity {
  BackgroundColor #EFEFEF
  BorderColor #2B2B2B
  BackgroundColor<<failure>> #FFEEEE
}

title Common Sub-Activity — Audit Event

|Audit|
start
:Record audit event;
stop
@enduml

